### ISSUE TITLE
Loader class is not working.

### ISSUE THREAD

**Issue by angelyarmas** [jtsternberg/Shortcode_Button#13]
Using the example code in the main page i got an error
`Class 'Shortcode_Button' not found in C:\wamp\www\wordpress\wp-content\plugins\shortcode-test\shortcode-test.php`

it seems that the problem is related to the loader class.
`$button = new Shortcode_Button( $button_slug, $js_button_data, $additional_args );`

i'm using the latest wordpress and CMB2 versions in a new wordpress enviroment.

**Comment by jtsternberg** [comment]
I updated the readme example. Please try again with that updated example.

**Comment by angelyarmas** [comment]
i got this error now, 
![image](https://cloud.githubusercontent.com/assets/24700606/22377135/b23a280e-e47e-11e6-972b-29a5cefeff5b.png)

for this section
```
/**
 * Callback dictates that shortcode button will only display if we're on a 'page' edit screen
 *
 * @return bool Expects a boolean value
 */
function shortcode_button_only_pages() {
    if ( ! is_admin() ) {
        return false;
    }

    $current_screen = get_current_screen();

    if ( ! isset( $current_screen->parent_base ) || $current_screen->parent_base != 'edit' ) {
        return false;
    }

    if ( ! isset( $current_screen->post_type ) || $current_screen->post_type != 'page' ) {
        return false;
    }

    // Ok, guess we're on a 'page' edit screen
    return true;
}
```

**Comment by jtsternberg** [comment]
ha, ok, just updated the example again. :)

**Comment by angelyarmas** [comment]
Thanks man, that fixes it.
