### ISSUE TITLE
Checkbox field styling

### ISSUE THREAD

**Issue by JiveDig** [jtsternberg/Shortcode_Button#18]
The checkbox field would look much better, and be much more usable, if it were styled like the multicheck_inline field, but obviously with only 1 value. 

Here is the checkbox field (last field in form):
<img width="600" alt="screen shot 2017-06-07 at 12 28 23 am" src="https://user-images.githubusercontent.com/540990/26862351-7eca7ea0-4b18-11e7-93f6-79f5bb1f33ef.png">

Here is the multicheck_inline field with 1 option:
<img width="584" alt="screen shot 2017-06-07 at 12 28 50 am" src="https://user-images.githubusercontent.com/540990/26862358-897956fa-4b18-11e7-95af-faf792797afa.png">

I would just use the multicheck_inline field but it doesn't parse correctly, I just need boolean but it's returning an array, naturally. I could filter with `*_shortcode_fields*, but then when I edit, it doesn't load correctly.

The easiest things seemed to be more consistent form styling for checkbox fields.

Let me know what you think.

**Comment by jtsternberg** [comment]
I agree, that does look much cleaner. Would you be willing to issue a PR? https://github.com/jtsternberg/Shortcode_Button/blob/master/css/shortcode-button.css
