### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by dnvgts** [jtsternberg/Shortcode_Button#3]
Hi.

I wanted to try this plugin but unfortunately I have this error when I try to insert the shortcode: Cannot access protected property CMB2::$data_to_save line 314

Can you help me?

Thanks
Danilo

**Comment by jtsternberg** [comment]
what happens if you change `class _Shortcode_Button_ {` to `class _Shortcode_Button_ extends CMB2 {`?

**Comment by dnvgts** [comment]
Hi.

Thanks for your reply. This is the error: Fatal error: Class 'CMB2' not found

**Comment by jtsternberg** [comment]
Ok, scratch that last suggestion. I've [updated CMB2](https://github.com/WebDevStudios/CMB2/commit/3804abb8199174353c38c79d7573cebd8a272462) to make `CMB2::$data_to_save` a public property and should alleviate that issue. Please update your copy of CMB2 and let me know. If you're using the WordPress plugin, you may want to make the change manually until it gets pushed up there.

**Comment by dnvgts** [comment]
Hi.

Thank you very much! Now everything works fine! Excellent work!

Kind Regards
Danilo

**Comment by jtsternberg** [comment]
:+1:
