### ISSUE TITLE
Long forms anchor at the bottom

### ISSUE THREAD

**Issue by erikberger** [jtsternberg/Shortcode_Button#9]
If you have a long form with a lot of fields the modal opens at the bottom of the form. Not a huge deal, but you do need to scroll up to see the beginning of the form. 

I believe that this is because the insert submit button is being focused on:

https://github.com/jtsternberg/Shortcode_Button/blob/master/js/shortcode-quicktag-button.js#L179

`$c.modal.find( '.scb-insert' ).trigger( 'focus' );`

Is it possible to focus on the first field instead?

**Comment by jtsternberg** [comment]
Hey @erikberger, I added a [tabindex to the modal](http://stackoverflow.com/a/32912224) and focus on that instead. Thanks for reporting.
